name: Build and Release

on:
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required to create the release and upload assets
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Install Pebble SDK
        run: |
          uv tool install pebble-tool --python 3.13
          pebble sdk install latest

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libsdl1.2debian libfdt1

      - name: Clean and Build
        run: |
          pebble clean
          pebble build

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ github.run_number }}
          files: build/*.pbw
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
